# Generated by Django 6.0.5 on 2026-06-21 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_driver'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverDailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=50, verbose_name='ドライバー名')),
                ('date', models.DateField(verbose_name='日付')),
                ('end_time', models.TimeField(verbose_name='業務終了時刻')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
            ],
            options={
                'verbose_name': '業務終了記録',
                'verbose_name_plural': '業務終了記録',
                'ordering': ['-date', 'driver_name'],
                'unique_together': {('driver_name', 'date')},
            },
        ),
    ]
